# Generated by Django 4.2.11 on 2026-01-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del producto', max_length=100, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', null=True, verbose_name='Descripción')),
                ('cantidad', models.IntegerField(default=0, help_text='Cantidad disponible en inventario', verbose_name='Cantidad en stock')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en COP (Pesos Colombianos)', max_digits=10, verbose_name='Precio unitario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto está activo en el sistema', verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Producto Local',
                'verbose_name_plural': 'Productos Locales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
