# Generated by Django 4.2.11 on 2026-01-13 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('initial', 'Stock Inicial'), ('transfer', 'Transferencia'), ('adjustment', 'Ajuste'), ('sale', 'Venta'), ('return', 'Devolución'), ('waste', 'Pérdida')], max_length=20)),
                ('from_location_type', models.CharField(blank=True, choices=[('general', 'Inventario General'), ('regional', 'Inventario Regional'), ('branch', 'Sucursal'), ('external', 'Externo'), ('supplier', 'Proveedor'), ('customer', 'Cliente'), ('waste', 'Pérdida')], max_length=20, null=True)),
                ('from_location_id', models.UUIDField(blank=True, null=True)),
                ('to_location_type', models.CharField(choices=[('general', 'Inventario General'), ('regional', 'Inventario Regional'), ('branch', 'Sucursal'), ('external', 'Externo'), ('supplier', 'Proveedor'), ('customer', 'Cliente'), ('waste', 'Pérdida')], max_length=20)),
                ('to_location_id', models.UUIDField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción de Inventario',
                'verbose_name_plural': 'Transacciones de Inventario',
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('requires_refrigeration', models.BooleanField(default=False)),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('special_conditions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('climate_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegionalInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_sku', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('special_conditions', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_inventories', to='inventory.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_inventories', to='inventory.product')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_inventories', to='inventory.region')),
            ],
            options={
                'verbose_name': 'Inventario Regional',
                'verbose_name_plural': 'Inventarios Regionales',
                'db_table': 'regional_inventory',
            },
        ),
        migrations.CreateModel(
            name='SpecialZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_code', models.CharField(max_length=50, unique=True)),
                ('zone_name', models.CharField(max_length=255)),
                ('region_name', models.CharField(max_length=100)),
                ('has_refrigeration_priority', models.BooleanField(default=False)),
                ('additional_requirements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductoLocal',
        ),
        migrations.CreateModel(
            name='GeneralInventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='general_inventory', serialize=False, to='inventory.product')),
                ('quantity', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(blank=True, null=True)),
                ('max_stock', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inventario General',
                'verbose_name_plural': 'Inventarios Generales',
                'db_table': 'general_inventory',
            },
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='inventory.region'),
        ),
        migrations.AddConstraint(
            model_name='regionalinventory',
            constraint=models.UniqueConstraint(fields=('product', 'branch'), name='unique_product_branch'),
        ),
        migrations.AlterUniqueTogether(
            name='regionalinventory',
            unique_together={('product', 'branch')},
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', 'created_at'], name='inventory_t_product_283f37_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['created_at'], name='inventory_t_created_f087fb_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type'], name='inventory_t_transac_a372b6_idx'),
        ),
    ]
