# Generated by Django 4.2.11 on 2026-01-13 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispatch_id', models.CharField(max_length=100, verbose_name='ID de Despacho')),
                ('note_type', models.CharField(choices=[('internal', 'Interna'), ('customer', 'Cliente'), ('driver', 'Conductor'), ('warehouse', 'Almacén'), ('other', 'Otro')], default='internal', max_length=20, verbose_name='Tipo de Nota')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('is_important', models.BooleanField(default=False, verbose_name='Importante')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creado Por (Usuario ID)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota de Despacho',
                'verbose_name_plural': 'Notas de Despachos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dispatch_id', 'note_type'], name='dispatches__dispatc_d53d75_idx'), models.Index(fields=['is_important'], name='dispatches__is_impo_26e6f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='DispatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispatch_id', models.CharField(max_length=100, verbose_name='ID de Despacho')),
                ('action', models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('status_changed', 'Estado Cambiado'), ('dispatched', 'Despachado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('note_added', 'Nota Agregada')], max_length=20, verbose_name='Acción')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Detalle de los cambios en formato JSON', null=True, verbose_name='Cambios Realizados')),
                ('performed_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Realizado Por (Usuario ID)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Despacho',
                'verbose_name_plural': 'Historiales de Despachos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dispatch_id', 'created_at'], name='dispatches__dispatc_b7a2a7_idx'), models.Index(fields=['action'], name='dispatches__action_1ee319_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispatch_code', models.CharField(max_length=100, unique=True, verbose_name='Código de Despacho')),
                ('branch_id', models.CharField(max_length=100, verbose_name='ID de Sucursal')),
                ('destination_zone_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Zona Destino')),
                ('shipment_type', models.CharField(choices=[('standard', 'Estándar'), ('refrigerated', 'Refrigerado'), ('express', 'Express'), ('fragile', 'Frágil')], default='standard', max_length=20, verbose_name='Tipo de Envío')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('preparing', 'Preparando'), ('dispatched', 'Despachado'), ('in_transit', 'En Tránsito'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('returned', 'Devuelto')], default='pending', max_length=20, verbose_name='Estado')),
                ('priority', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta'), (4, 'Urgente')], default=2, verbose_name='Prioridad')),
                ('products', models.JSONField(default=list, help_text="Lista de productos en formato JSON: [{'product_id': 'uuid', 'quantity': 10, 'product_name': '...'}]", verbose_name='Productos Despachados')),
                ('requires_refrigeration', models.BooleanField(default=False, verbose_name='Requiere Refrigeración')),
                ('temperature_range', models.CharField(blank=True, help_text="Ej: '2°C - 6°C'", max_length=50, null=True, verbose_name='Rango de Temperatura')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='Instrucciones Especiales')),
                ('scheduled_date', models.DateField(verbose_name='Fecha Programada')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Despacho')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creado Por (Usuario ID)')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dispatch_code'], name='dispatches__dispatc_87276d_idx'), models.Index(fields=['status'], name='dispatches__status_6cb10e_idx'), models.Index(fields=['scheduled_date'], name='dispatches__schedul_80646a_idx'), models.Index(fields=['branch_id', 'status'], name='dispatches__branch__20330f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Destino')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Persona de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('special_zone_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Zona Especial')),
                ('requires_refrigeration_access', models.BooleanField(default=False, verbose_name='Requiere Acceso a Refrigeración')),
                ('delivery_hours', models.CharField(blank=True, help_text="Ej: 'Lunes a Viernes 8:00-18:00'", max_length=100, null=True, verbose_name='Horario de Entrega')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='dispatches__name_7f652f_idx'), models.Index(fields=['is_active'], name='dispatches__is_acti_88cae7_idx')],
            },
        ),
    ]
